# Generated by Django 3.2.4 on 2021-06-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proname', models.CharField(blank=True, max_length=100, null=True)),
                ('Brand', models.CharField(blank=True, choices=[('1', 'BMW'), ('2', 'Nessan'), ('3', 'Tyota')], max_length=8, null=True)),
            ],
        ),
    ]
