# Generated by Django 3.2.4 on 2021-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210625_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to='phtop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='Brand',
            field=models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Nessan', 'Nessan'), ('Tyota', 'Tyota')], max_length=8, null=True),
        ),
    ]
